Grant.Web/Models/ViewModels/ManageThematicViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Grant.Web.Models.ViewModels
{
    public class ManageThematicViewModel
    {
        public int ThematicId { get; set; }//pk

        public string Name { get; set; }

        public string Description { get; set; }

        public string Code { get; set; }

        [Display(Name = "Select Thematic Category")]
        public int CategoryId { get; set; }

        [Display(Name = "Category Name")]
        public string CategoryName { get; set; }

        [Display(Name = "Category Description")]
        public string CategoryDescription { get; set; }

        public List<SelectListItem> CategorySL { get; set; }

        public List<Theme> Themes { get; set; } = new List<Theme>();

        public List<Category> Categories { get; set; } = new List<Category>();
    }
}

Grant.Web/Controllers/ManageThematicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Grant.Web.Infrastructure;
using Grant.Web.Models;
using Grant.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Grant.Web.Controllers
{
    [Authorize(Policy = "MustBeAdmin")]
    public class ManageThematicController : BaseController
    {
        private ManageThematicViewModel _viewModel;
        private DataBaseContext _context;
        private Utility _utility;

        public ManageThematicController(DataBaseContext context, Utility utility)
        {
            _context = context;
            _utility = utility;
            _viewModel = new ManageThematicViewModel();
        }

        public IActionResult Index()
        {
            var themeList = _context.Theme
                                    .Where(t => t.Active)
                                    .OrderBy(t => t.Name)
                                    .ToList();

            _viewModel.Themes = themeList;

            return View(_viewModel);
        }

        public IActionResult AddThematicTheme()
        {
            try
            {
                _viewModel.CategorySL = _utility.GetCategorySL();
                return View(_viewModel);
            }
            catch (Exception ex) { throw ex; }
        }

        [HttpPost]
        public IActionResult AddThematicTheme(ManageThematicViewModel viewModel)
        {
            try
            {
                if (!string.IsNullOrEmpty(viewModel.Name))
                {
                    var theme = new Theme()
                    {
                        Name = viewModel.Name,
                        Description = string.IsNullOrEmpty(viewModel.Description) ? viewModel.Name : viewModel.Description,
                        Active = true,
                        CategoryId = viewModel.CategoryId,
                        Code = viewModel.Code
                    };

                    _context.Add(theme);
                    _context.SaveChanges();

                    SetMessage("Theme was added successfully");

                    return RedirectToAction("AddThematicTheme");
                }
                return View(viewModel);
            }
            catch (Exception ex) { throw ex; }
        }
        
        public IActionResult EditThematicTheme(int Id)
        {
            try
            {
                if (Id < 1)
                {
                    return RedirectToAction("Index");
                }

                var theme = _context.Theme.Where(t => t.Id == Id).FirstOrDefault();
                if (theme != null)
                {
                    _viewModel.Name = theme.Name;
                    _viewModel.Description = theme.Description;
                    _viewModel.CategoryId = theme.Id;
                    _viewModel.Code = theme.Code;
                    _viewModel.CategoryId = theme.CategoryId;
                }

                _viewModel.ThematicId = Id;
                _viewModel.CategorySL = _utility.GetCategorySL();

                return View(_viewModel);
            }
            catch (Exception ex) { throw ex; }
        }

        [HttpPost]
        public IActionResult EditThematicTheme(ManageThematicViewModel viewModel)
        {
            try
            {
                if (!string.IsNullOrEmpty(viewModel.Name) && viewModel.CategoryId > 0)
                {
                    var theme = _context.Theme.Where(t => t.Id == viewModel.CategoryId).FirstOrDefault();
                    if (theme != null)
                    {
                        theme.Name = viewModel.Name;
                        theme.Description = viewModel.Description;
                        theme.CategoryId = viewModel.CategoryId;
                        theme.Code = viewModel.Code;

                        _context.Update(theme);
                        _context.SaveChanges();

                        SetMessage("Theme was updated successfully");

                        return RedirectToAction("EditThematicTheme", new { Id = theme.Id });
                    }
                }
                return View(viewModel);
            }
            catch (Exception ex) { throw ex; }
        }

        public IActionResult ViewAllCategories()
        {
            try
            {
                _viewModel.Categories = _context.Category.ToList();
                return View(_viewModel);
            }
            catch(Exception ex) { throw ex; }
        }

        public IActionResult AddCategory()
        {
            try
            {
                return View();
            }
            catch (Exception ex) { throw ex; }
        }

        [HttpPost]
        public IActionResult AddCategory(ManageThematicViewModel viewModel)
        {
            try
            {
                if (!string.IsNullOrEmpty(viewModel.CategoryName))
                {
                    var categoryExists = _context.Category.Where(c => c.Name == viewModel.CategoryName).FirstOrDefault();
                    if (categoryExists == null)
                    {
                        var category = new Category()
                        {
                            Name = viewModel.CategoryName,
                            Description = viewModel.CategoryDescription,
                            Code = viewModel.Code,
                            Active = true
                        };

                        _context.Add(category);
                        _context.SaveChanges();

                        SetMessage("Category created successfully");
                    }
                    else
                    {
                        SetMessage("Category already exists");
                    }
                }
                else
                {
                    SetMessage("Please fill in all required fields");
                }

                return RedirectToAction("AddCategory");
            }
            catch (Exception ex) { throw ex; }
        }

        public IActionResult EditCategory(int Id)
        {
            try
            {
                if (Id < 1)
                {
                    return RedirectToAction("ViewAllCategories");
                }

                var category = _context.Category.Where(c => c.Id == Id).FirstOrDefault();
                if (category != null)
                {   
                    _viewModel.CategoryName = category.Name;
                    _viewModel.CategoryDescription = category.Description;
                    _viewModel.Code = category.Code;
                }
                _viewModel.CategoryId = Id;

                return View(_viewModel);
            }
            catch(Exception ex) { throw ex; }
        }

        [HttpPost]
        public IActionResult EditCategory(ManageThematicViewModel viewModel)
        {
            try
            {
                if (viewModel.CategoryId < 1)
                {
                    return RedirectToAction("ViewAllCategories");
                }

               if(!string.IsNullOrEmpty(viewModel.CategoryName))
               {
                    var category = _context.Category.Where(c => c.Id == viewModel.CategoryId).FirstOrDefault();
                    if (category != null)
                    {
                        category.Name = viewModel.CategoryName;
                        category.Description = viewModel.CategoryDescription;
                        category.Code = viewModel.Code;

                        _context.Update(category);
                        _context.SaveChanges();

                        SetMessage("Category updated successfully");
                    }
                }
                else
                {
                    SetMessage("Please fill in all required fields");
                }

                return View(viewModel);
            }
            catch (Exception ex) { throw ex; }
        }

        [HttpPost]
        public IActionResult DeactivateCategory(int id)
        {
            try
            {
                var category = _context.Category.Where(m => m.Id == id).FirstOrDefault();

                if (category != null)
                {
                    bool active = category.Active;

                    category.Active = !category.Active;
                    _context.Update(category);
                    _context.SaveChanges();

                    string msg = string.Format("'{0}' was {1} successfully", category.Name, (active == true ? "Deactivated" : "Activated"));
                    return Json(msg);
                }

                return RedirectToAction("ViewAllCategories");
            }
            catch (Exception ex) { throw ex; }
        }

        [HttpPost]
        public IActionResult DeactivateTheme(int id)
        {
            try
            {
                var theme = _context.Theme.Where(m => m.Id == id).FirstOrDefault();

                if (theme != null)
                {
                    bool active = theme.Active;

                    theme.Active = !theme.Active;
                    _context.Update(theme);
                    _context.SaveChanges();

                    string msg = string.Format("'{0}' was {1} successfully", theme.Name, (active == true ? "Deactivated" : "Activated"));
                    return Json(msg);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex) { throw ex; }
        }
    }
}

Grant.Web/Views/ManageThematic/AddCategory.cshtml
@model Grant.Web.Models.ViewModels.ManageThematicViewModel
@{
    ViewData["Title"] = "Add Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">
            <partial name="_Message" model="@TempData["Message"]" />
        </div>
    }
</section>

<section class="content">

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Category <span class="text-sm text-muted">/ Add Category</span></h1>
    </div>

    <div class="row justify-content-center" style="margin-bottom: 30px">
        <div class="col-md-8">
            <!-- Horizontal Form -->
            <div class="card animated fadeInUp delay-1s">
                <div class="card-body">
                    <form asp-action="AddCategory" asp-controller="ManageThematic">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="CategoryName" class="control-label"></label>
                            <input asp-for="CategoryName" class="form-control" required />
                            <span asp-validation-for="CategoryName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Code" class="control-label"></label>
                            <input asp-for="Code" class="form-control" required />
                            <span asp-validation-for="Code" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CategoryDescription" class="control-label"></label>
                            <textarea asp-for="CategoryDescription" class="form-control" style="resize: none;"></textarea>
                            <span asp-validation-for="CategoryDescription" class="text-danger"></span>
                        </div>

                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Grant.Web/Views/ManageThematic/AddThematicTheme.cshtml
@model Grant.Web.Models.ViewModels.ManageThematicViewModel
@{
    ViewData["Title"] = "Add Thematic Theme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">
            <partial name="_Message" model="@TempData["Message"]" />
        </div>
    }
</section>

<section class="content">

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Thematic Areas <span class="text-sm text-muted">/ Add Theme</span></h1>
    </div>

    <div class="row justify-content-center" style="margin-bottom: 30px">
        <div class="col-md-8">
            <!-- Horizontal Form -->
            <div class="card animated fadeInUp delay-1s" >
                <div class="card-body">
                    <form asp-action="AddThematicTheme" asp-controller="ManageThematic">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" required />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <textarea asp-for="Description" class="form-control" style="resize: none;"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Code" class="control-label"></label>
                            <input asp-for="Code" class="form-control" required />
                            <span asp-validation-for="Code" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CategoryId" class="control-label"></label>
                            <select asp-for="CategoryId" class="form-control" asp-items="Model.CategorySL" required></select>
                            <span asp-validation-for="CategoryId" class="text-danger"></span>
                        </div>

                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Grant.Web/Views/ManageThematic/EditCategory.cshtml
@model Grant.Web.Models.ViewModels.ManageThematicViewModel
@{
    ViewData["Title"] = "Edit Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">
            <partial name="_Message" model="@TempData["Message"]" />
        </div>
    }
</section>

<section class="content">

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Category <span class="text-sm text-muted">/ Edit Category</span></h1>
    </div>

    <div class="row justify-content-center" style="margin-bottom: 30px">
        <div class="col-md-8">
            <!-- Horizontal Form -->
            <div class="card animated fadeInUp delay-1s">
                <div class="card-body">
                    <form asp-action="EditCategory" asp-controller="ManageThematic">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <input asp-for="CategoryId" type="hidden" />

                        <div class="form-group">
                            <label asp-for="CategoryName" class="control-label"></label>
                            <input asp-for="CategoryName" class="form-control" required />
                            <span asp-validation-for="CategoryName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Code" class="control-label"></label>
                            <input asp-for="Code" class="form-control" required />
                            <span asp-validation-for="Code" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CategoryDescription" class="control-label"></label>
                            <textarea asp-for="CategoryDescription" class="form-control" style="resize: none;"></textarea>
                            <span asp-validation-for="CategoryDescription" class="text-danger"></span>
                        </div>

                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-success"><i class="fa fa-pencil"></i> Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Grant.Web/Views/ManageThematic/EditThematicTheme.cshtml
@model Grant.Web.Models.ViewModels.ManageThematicViewModel
@{
    ViewData["Title"] = "Edit Thematic Theme";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">
            <partial name="_Message" model="@TempData["Message"]" />
        </div>
    }
</section>

<section class="content">

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Thematic Areas <span class="text-sm text-muted">/ Edit Theme</span></h1>
    </div>

    <div class="row justify-content-center" style="margin-bottom: 30px">
        <div class="col-md-8">
            <!-- Horizontal Form -->
            <div class="card animated fadeInUp delay-1s" >
                <div class="card-body">
                    <form asp-action="EditThematicTheme" asp-controller="ManageThematic">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input asp-for="ThematicId" type="hidden" />

                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" required />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <textarea asp-for="Description" class="form-control" style="resize: none;"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Code" class="control-label"></label>
                            <input asp-for="Code" class="form-control" required />
                            <span asp-validation-for="Code" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CategoryId" class="control-label"></label>
                            <select asp-for="CategoryId" class="form-control" asp-items="Model.CategorySL" required></select>
                            <span asp-validation-for="CategoryId" class="text-danger"></span>
                        </div>

                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-success"><i class="fa fa-pencil"></i> Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

Grant.Web/Views/ManageThematic/Index.cshtml
@model Grant.Web.Models.ViewModels.ManageThematicViewModel
@{
    ViewData["Title"] = "View All Themes";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">
            <partial name="_Message" model="@TempData["Message"]" />
        </div>
    }
</section>

<div class="content" >

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Thematic Areas / <span class="text-sm text-muted">View Theme</span></h1>
        <div class="avatar-group mt-3">
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-10">
            <!-- Horizontal Form -->
            <div class="card" >
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="modelDataTable" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        SN
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>Code</th>

                                    <th>
                                        Description
                                    </th>
                                    <th>Category</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @{ int index = 0; }
                                @foreach (var item in Model.Themes)
                                {
                                    index += 1;
                                    <tr>
                                        <td>
                                            @index
                                        </td>
                                        <td class="text-capitalize">
                                            @item.Name
                                        </td>
                                        <td>@item.Code</td>
                                        <td>
                                            @item.Description
                                        </td>
                                        <td>
                                            @item.Category.Name
                                        </td>
                                        <td>
                                            @if (item.Active)
                                            {
                                                <input type="checkbox" checked onclick="deactivateTheme(@item.Id)" />
                                            }
                                            else
                                            {
                                                <input type="checkbox" onclick="deactivateTheme(@item.Id)" />
                                            }
                                        </td>
                                        <td>
                                            <a asp-action="EditThematicTheme" asp-controller="ManageThematic" class="btn btn-success" asp-route-id="@item.Id">Edit</a>
                                        </td>
                                    </tr>
                                 }
                            </table>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <a class="btn btn-success" asp-action="AddThematicTheme" asp-controller="ManageThematic">Add Theme</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function deactivateTheme(id) {
        if (id) {
            $.ajax({
                type: "POST",
                url: "@Url.Action("DeactivateTheme", "ManageThematic")",
                data: { id },
                dataType: "json",
                success: function (data) {
                    alert(data);
                },
                error: function (error) {
                    console.error(error);
                }
            });
        }
    }
</script>

Grant.Web/Views/ManageThematic/ViewAllCategories.cshtml
@model Grant.Web.Models.ViewModels.ManageThematicViewModel
@{
    ViewData["Title"] = "View All Categories";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">
            <partial name="_Message" model="@TempData["Message"]" />
        </div>
    }
</section>

<div class="content">

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Category <span class="text-sm text-muted">/ View Categories</span></h1>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-10">
            <!-- Horizontal Form -->
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="modelDataTable" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        SN
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>Code</th>
                                    <th>
                                        Description
                                    </th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @{ int index = 0; }
                                @foreach (var item in Model.Categories)
                                {
                                    index += 1;
                                    <tr>
                                        <td>
                                            @index
                                        </td>
                                        <td class="text-capitalize">
                                            @item.Name
                                        </td>
                                        <td>@item.Code</td>
                                        <td>
                                            @item.Description
                                        </td>
                                        <td>
                                            @if (item.Active)
                                            {
                                                <input type="checkbox" checked onclick="deactivateCategory(@item.Id)" />
                                            }
                                            else
                                            {
                                                <input type="checkbox" onclick="deactivateCategory(@item.Id)" />
                                            }
                                        </td>
                                        <td>
                                            <a asp-action="EditCategory" asp-controller="ManageThematic" class="btn btn-success" asp-route-id="@item.Id">Edit</a>
                                        </td>
                                    </tr>
                                }
                        </table>
                    </div>
                </div>
                <div class="card-footer text-center">
                    <a class="btn btn-success" asp-action="AddCategory" asp-controller="ManageThematic">Add Category</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function deactivateCategory(id) {
        if (id) {
            $.ajax({
                type: "POST",
                url: "@Url.Action("DeactivateCategory", "ManageThematic")",
                data: { id },
                dataType: "json",
                success: function (data) {
                    alert(data);
                },
                error: function (error) {
                    console.error(error);
                }
            });
        }
    }
</script>