Grant.Web/Controllers/BulletinBoardController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Grant.Web.Infrastructure;
using Grant.Web.Models;
using Grant.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Grant.Web.Controllers
{
    [Authorize(Policy = "MustBeApplicant")]
    public class BulletinBoardController : BaseController
    {
        private readonly DataBaseContext _context;
        private readonly Utility _utility;
        BulletinViewModel _viewModel;
        IHostingEnvironment _hostingEnvironment;

        public BulletinBoardController(DataBaseContext context, Utility utility, IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
            _utility = utility;
            _viewModel = new BulletinViewModel();
            _viewModel.SetViewModelProperties(_context);
        }
        public IActionResult CreateBulletinTopic()
        {
            string personEmail = User.FindFirstValue(ClaimTypes.Email);
            string roleName = User.FindFirstValue(ClaimTypes.Role);
            if (personEmail != null)
            {

                var applicantThematic = new ApplicantThematic();
                var person = _context.Person.Where(f => f.Email == personEmail).FirstOrDefault();
                if (roleName == "Co-Applicant")
                {
                    string teamThematic = User.FindFirstValue(ClaimTypes.GroupSid);
                    var applicantThematiceId = Convert.ToInt32(teamThematic);
                    applicantThematic = _context.ApplicantThematic.Where(f => f.Id == applicantThematiceId).FirstOrDefault();

                }
                else
                {
                    applicantThematic = _context.ApplicantThematic.Where(f => f.Applicant.PersonId == person.Id && f.Applicant.RoleId == (int)Roles.Applicant && f.Session.ActiveForApplication).FirstOrDefault();
                   
                }
                if (applicantThematic == null)
                {
                    SetMessage("Please add a Research Topic to continue");
                    return RedirectToAction("Index","userhome");
                }


            }
            else
            {
                return RedirectToAction("Logout", "Home");
            }
            return View(_viewModel);
        }

        [HttpPost]
        public IActionResult CreateBulletinTopic(BulletinViewModel bulletinViewModel)
        {
            if (bulletinViewModel.BulletinTopic.Topic != null)
            {
                string personEmail = User.FindFirstValue(ClaimTypes.Email);
                string roleName = User.FindFirstValue(ClaimTypes.Role);
                if (personEmail != null)
                {
                    var applicantThematic = new ApplicantThematic();
                    var person=_context.Person.Where(f => f.Email == personEmail).FirstOrDefault();
                    if (roleName == "Co-Applicant")
                    {
                        string teamThematic = User.FindFirstValue(ClaimTypes.GroupSid);
                        var applicantThematiceId = Convert.ToInt32(teamThematic);
                        applicantThematic=_context.ApplicantThematic.Where(f => f.Id == applicantThematiceId).FirstOrDefault();

                    }
                    else
                    {
                        applicantThematic = _context.ApplicantThematic.Where(f => f.Applicant.PersonId==person.Id && f.Applicant.RoleId==(int)Roles.Applicant && f.Session.ActiveForApplication).FirstOrDefault();
                    }
                    
                    var topicCreated=_utility.CreateBulletinTopic(bulletinViewModel.BulletinTopic, person, applicantThematic);
                    if (topicCreated?.Id > 0)
                    {
                        return RedirectToAction("ViewAllBulletinActiveTopic");
                    }
                   
                }
                else
                {
                    return RedirectToAction("Logout", "Home");
                }
                
            }
            else
            {
                SetMessage("Kindly enter a Topic to continue");
            }
            return View(bulletinViewModel);
        }

        public IActionResult ViewAllBulletinActiveTopic()
        {
            try
            {
                string personEmail = User.FindFirstValue(ClaimTypes.Email);
                string roleName = User.FindFirstValue(ClaimTypes.Role);
                if (personEmail != null)
                {

                    var applicantThematic = new ApplicantThematic();
                    var person = _context.Person.Where(f => f.Email == personEmail).FirstOrDefault();
                    if (roleName == "Co-Applicant")
                    {
                        string teamThematic = User.FindFirstValue(ClaimTypes.GroupSid);
                        var applicantThematiceId = Convert.ToInt32(teamThematic);
                        applicantThematic = _context.ApplicantThematic.Where(f => f.Id == applicantThematiceId).FirstOrDefault();
                        if (applicantThematic == null)
                        {
                            SetMessage("Please add a Research Topic to continue");
                            return RedirectToAction("Index", "userhome");
                        }

                    }
                    else
                    {
                        applicantThematic = _context.ApplicantThematic.Where(f => f.Applicant.PersonId == person.Id && f.Applicant.RoleId == (int)Roles.Applicant && f.Session.ActiveForApplication).FirstOrDefault();
                        if (applicantThematic == null)
                        {
                            SetMessage("Please add a Research Topic to continue");
                            return RedirectToAction("Index", "userhome");
                        }
                    }

                        _viewModel.SetBulletinTopics(applicantThematic);

                }
                else
                {
                    return RedirectToAction("Logout", "Home");
                }

            }
            catch (Exception ex)
            {

                throw ex;
            }
            return View(_viewModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult SendMessageWithoutAttachment(IFormCollection form)
        {
            JsonResultModel result = new JsonResultModel();
            try
            {   
                string message = (form["Message"]);
                var bulletinTopicId = (form["bulletinId"])[0];
                string fileName = "";

                if (!(string.IsNullOrEmpty(message) && string.IsNullOrEmpty(bulletinTopicId)))
                {
                    string personEmail = User.FindFirstValue(ClaimTypes.Email);

                    long bulletinId = Convert.ToInt64(bulletinTopicId);

                    var attachementPath = "";
                    var person = _context.Person.Where(f => f.Email == personEmail).FirstOrDefault();
                    _utility.SaveChatResponse(bulletinId, person, message, attachementPath,fileName);

                    result.IsError = false;
                }
            }
            catch(Exception ex)
            {
                result.IsError = true;
                result.Message = ex.Message;
            }

            return Json(result);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> SendMessage(IFormCollection form, IFormFile AttachmentFile)
        {
            JsonResultModel result = new JsonResultModel();
            try
            {   
                string message = (form["Message"]);
                var bulletinTopicId = (form["bulletinId"])[0];
                string filePath = "";
                string fileName = "";

                if ((!(string.IsNullOrEmpty(message) && string.IsNullOrEmpty(bulletinTopicId)))|| !(AttachmentFile.Length>0 && !String.IsNullOrEmpty(bulletinTopicId)))
                {
                    string personEmail = User.FindFirstValue(ClaimTypes.Email);
                    long bulletinId = Convert.ToInt64(bulletinTopicId);

                    var person = _context.Person.Where(f => f.Email == personEmail).FirstOrDefault();

                    if (AttachmentFile.Length > 0)
                    {
                        var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "attachments");
                        var extName = Path.GetExtension(AttachmentFile.FileName);
                        fileName = Path.GetFileName(AttachmentFile.FileName);
                        string saveName = string.Format("Attachment_{0}_{1}{2}", DateTime.Now.Second, DateTime.Now.Millisecond, extName);
                        filePath = Path.Combine(uploads, saveName);

                        FileInfo file = new FileInfo(saveName);
                        if (file.Exists)
                        {
                            file.Delete();
                        }

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await AttachmentFile.CopyToAsync(stream);
                        }
                        //filePath = string.Format("~/Grant.Web/attachments/{0}", saveName);
                        filePath = "\\attachments\\" + saveName;

                    }
                    _utility.SaveChatResponse(bulletinId, person, message, filePath, fileName);
                    result.IsError = false;
                    result.Message = filePath;
                }
            }
            catch(Exception ex)
            {
                result.IsError = true;

Grant.Web/Views/BulletinBoard/CreateBulletinTopic.cshtml
@model Grant.Web.Models.ViewModels.BulletinViewModel
@{
    ViewData["Title"] = "Create Bulletin Topic";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    <div class="pg-head">
        <h3 class="monts text-center" style="font-weight: 300; margin-top: 10px">Create Discussion Topic</h3>
    </div>

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">

            @Html.Partial("_Message", TempData["Message"])

        </div>
    }
</section>

<section class="content">
    <div class="container" style="margin-bottom: 30px">

        <div class="">

            <div class="col-md-12">
                <!-- Horizontal Form -->
                <div class="box box-danger" style="border-top-color: #fff; border-radius: 0">

                    <div class="box-body">
                     
                        <form asp-action="CreateBulletinTopic" asp-controller="BulletinBoard" method="POST" role="form" class="form-horizontal">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">


                                <label asp-for="BulletinTopic.Topic" class="col-sm-12">Discussion Topic</label>
                                    <div class="col-sm-12">
                                        <input asp-for="BulletinTopic.Topic" class="form-control" />
                                        <span asp-validation-for="BulletinTopic.Topic" class="text-danger"></span>
                                    </div>
                            </div>
                            <div class="box-footer">

                                <button type="submit" class="btn btn-success pull-right">Create Discussion Topic</button>
                            </div>
                        </form>
                    </div>


                </div>
            </div>


        </div>
    </div>
</section>

<script src="~/theme/bower_components/jquery/dist/jquery.js"></script>

Grant.Web/Views/BulletinBoard/JoinBulletinBoard.cshtml
@model Grant.Web.Models.ViewModels.BulletinViewModel
@{
    ViewData["Title"] = "Chat Board";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<style>
    body {
        font-family: Montserrat;
    }

    .bg-custom {
        background-color: #5FB9B0;
    }

    .message-box {
        margin-top: 40px;
        padding-left: 50px;
        padding-right: 50px
    }


    .recipient-msg {
        border-radius: 10px;
        padding: 20px;
        margin-bottom: 30px;
        color: #fff;
        background: #00BFA5;
        padding: 1em;
        width: -webkit-fit-content;
        width: -moz-fit-content;
        width: fit-content;
        margin: 1em 5px;
        max-width: 60%;
        position: left;
    }


    .sender-msg {
        border-radius: 10px;
        padding: 20px;
        margin-bottom: 30px;
        color: #000;
        background: #efe9ce;
        padding: 1em;
        width: -webkit-fit-content;
        width: -moz-fit-content;
        width: fit-content;
        margin: 1em 5px;
        max-width: 60%;
        text-align: right;
        right: 0px;
    }

    .msg-text {
        font-size: 15px;
    }

    .date-text {
        font-size: 11px;
        margin-bottom: 0px;
        text-align: right;
    }

    .jus-left {
        justify-content: end;
    }

    .push-right {
        margin-left: auto;
    }

    .message-input {
        background-color: #efe9ce;
        padding: 20px
    }

    .date {
        background-color: #92a6c6;
        padding: .7em;
        width: -webkit-fit-content;
        width: -moz-fit-content;
        width: fit-content;
        margin: 1em auto;
        border-radius: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        margin-top: 0;
    }

        .date p {
            font-weight: 400;
            margin-bottom: 0;
            color: #fff;
            font-size: 14px;
        }
</style>
<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    <div class="pg-head">
        <h3 class="monts text-center" style="font-weight: 300; margin-top: 10px">Bulletin Board</h3>
    </div>

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">

            @Html.Partial("_Message", TempData["Message"])

        </div>
    }
</section>

<section class="content">
    <div class="container" style="margin-bottom: 30px">
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="box box-danger" style="border-top-color: #fff; border-radius: 0">

                @*<div class="box-body">*@
                @Html.HiddenFor(m => m.ChatTopicId )
                <div class="container-fluid bg-custom">
                    <div class="py-4 pl-3 text-light">
                        <h2 class="">@Model.BulletinTopic.Topic</h2>
                        <h4><i class="fa fa-user-circle"></i> @Model.Person.ApplicantFullName</h4>
                    </div>
                </div>

                <div class="message-box" id="message-box"></div>

                <div class="message-input">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-2 pull-right">
                            <form class="send-msg-form" enctype="multipart/form-data">
                                <div class=" row mb-3">
                                    <div class="col-md-8">
                                        <textarea class="form-control" 
                                                  style="resize:none;" 
                                                  required 
                                                  placeholder="Enter message" 
                                                  aria-label="Recipient's username" 
                                                  aria-describedby="basic-addon2" 
                                                  name="Message"
                                                  id="responseMessage"></textarea>
                                    </div>
                                    <div class="col-md-1">
                                        <input type="file" 
                                               id="add-attachment" 
                                               class="btn btn-info" 
                                               
                                               name="AttachmentFile"
                                               style="display:none;" />

                                        <button type="button" class="btn btn-info" id="attachBtn"onclick="$('#add-attachment').trigger('click')">
                                            <i class="fa fa-paperclip"></i>
                                        </button>
                                        <button type="button" class="btn btn-sm btn-danger" style="display:none" id="cancleAttachement">Remove</button>
                                    </div>
                                    <div class="col-md-2">
                                        <button type="submit" 
                                                class="btn btn-secondary" 
                                                id="basic-addon2">Send <i class="fa fa-paper-plane"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="~/theme/bower_components/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    let bulletinTopicId = 0;
    $(document).ready(function () {
        bulletinTopicId = $('#@Html.IdFor(m => m.ChatTopicId)').val();
        loadChat();

        $(".send-msg-form").on("submit", function (e) {
            e.preventDefault();
            
            let response = $('#responseMessage').val();
            if ((response != null || $("#add-attachment").val()!=null) && response != undefined) {
                let attachmentFile = $("#add-attachment");

                let url_path = attachmentFile.val() ? "@(Url.Action("SendMessage", "BulletinBoard"))" : "@(Url.Action("SendMessageWithoutAttachment", "BulletinBoard"))"
                let formData = new FormData(this);
                formData.append("bulletinId", bulletinTopicId);
                $('#basic-addon2').text("Sending...");
                $('#basic-addon2').attr('disabled',true);

                $.ajax({
                    url: url_path,
                    type: "POST",
                    processData: false,
                    contentType: false,
                    data: formData,
                    success: function (result) {
                        console.log(result);
                        if (!result.isError) {
                            $('#cancleAttachement').hide();
                            $('#attachBtn').show();
                            loadChat(); $('#responseMessage').val('');
                        }
                    },
                    error: function (ex) {
                        alert('Failed to retrieve messages, refresh and try again');
                    }
                });
            }
        })

        //Validate image to make sure that file size criteria is met
        $("#add-attachment").on("change", function () {
            let validType = new RegExp('^.*\.(jpg|jpeg|png|gif|pdf|vnd.openxmlformats-officedocument.wordprocessingml.document|vnd.ms-excel|vnd.openxmlformats-officedocument.spreadsheetml.sheet)$');
            //let validType = new RegExp('(.*?)\.(jpg|jpeg|png|gif|pdf|DOC|docx|xls|xlsx)$');
            let fileType = this.files[0].type;

            if (this.files[0].size > 20000000) {
                alert("Please upload file less than 20MB. Thanks!!");
                $(this).val('');
                $('#cancleAttachement').hide();
                $('#attachBtn').show();
                
                
            }
            //validate against valid types
            if (!validType.test(fileType.toLowerCase())) {
                let fileTypeExt = fileType.split('/')[1];
                //let message = `'${fileTypeExt}' is invalid!! Only accepted types are: 'jpg', 'jpeg', 'png', 'gif', 'pdf','doc','docx','xls','xlsx'`;
                let message = `Invalid file format!! Acceptable file formats are: 'jpg', 'jpeg', 'png', 'gif', 'pdf','doc','docx','xls','xlsx'`;
                alert(message);
                $(this).val('');
                $('#cancleAttachement').hide();
                $('#attachBtn').show();
                
            }
            else {
                $('#attachBtn').hide();
                $('#cancleAttachement').show();
                
            }
        });
        $('#cancleAttachement').on('click', function () {
            
            $("#add-attachment").val('');
            $('#cancleAttachement').hide();
            $('#attachBtn').show();
            
        })
    })

    function loadChat() {
        if (bulletinTopicId > 0) {
             $.ajax({
                 type: 'POST',
                 url: '@Url.Action("AjaxLoadChatBoard", "BulletinBoard")', // we are calling json method
                 dataType: 'json',
                 data: { bulletinTopicId},
                 success: function (result) {
                     if (!result.isError) {
                         if (result.bulletinChatResponses && result.bulletinChatResponses.length > 0) {
                             let messageBox = $("#message-box");
                             messageBox.empty();//Clear all earlier content from the message box
                             let messageBoxContent = "";

                             //localStorage.setItem("Messages", JSON.stringify(result.bulletinChatResponses));
                             result.bulletinChatResponses.forEach(chatMessage => {

                                 if (!chatMessage.activeSender) {
                                     messageBoxContent += `<div class="recipient-msg">
                                            <h6>${chatMessage.sender}</h6>
                                            <p class="msg-text">
                                                ${chatMessage.response}
                                            </p>`;
                                     if (chatMessage.filePath && chatMessage.filePath !== "") {
                                         if (chatMessage.fileName != null) {
                                             var displayName = chatMessage.fileName.substring(0, 20) +"...";
                                         }
                                         messageBoxContent += `<a href='${chatMessage.filePath}' download='${chatMessage.fileName}' class='attachment-link'>${cdisplayName}</a>`;
                                     }
                                     messageBoxContent +=  `<p class="date-text">${chatMessage.dateSent}</p></div>`;
                                 }
                                 else {
                                     messageBoxContent += `<div class="sender-msg push-right">
                                                    <h6>${chatMessage.sender}</h6 >
                                                    <p class="msg-text">
                                                        ${chatMessage.response}
                                                    </p>`;

                                     if (chatMessage.filePath && chatMessage.filePath !== "") {
                                         if (chatMessage.fileName != null) {
                                             var displayName = chatMessage.fileName.substring(0, 20) + "...";
                                         }
                                         messageBoxContent += `<a href='${chatMessage.filePath}' download='${chatMessage.fileName}' class='attachment-link'>${displayName}</a>`;
                                     }
                                     messageBoxContent += `<p class="date-text">${chatMessage.dateSent}</p></div>`;
                                 }
                             });
                             $('#basic-addon2').text("Send");
                             $('#basic-addon2').attr('disabled', false);
                             $("#add-attachment").val('');
                             messageBox.html(messageBoxContent);
                         }
                     }
                 },
                 error: function (ex) {
                     alert('Failed to retrieve messages, refresh and try again');
                 }
             });
        }
               
        }
</script>

Grant.Web/Views/BulletinBoard/ViewAllBulletinActiveTopic.cshtml
@model Grant.Web.Models.ViewModels.BulletinViewModel
@{
    ViewData["Title"] = "All Active Topics";
    Layout = "~/Views/Shared/_UserLayout.cshtml";

}


<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    <div class="pg-head">
        <h3 class="monts text-center" style="font-weight: 300; margin-top: 10px">Active Discussion Topics</h3>
    </div>

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">

            @Html.Partial("_Message", TempData["Message"])

        </div>
    }
</section>

<section class="content">
    <div class="container" style="margin-bottom: 30px">
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="box box-danger" style="border-top-color: #fff; border-radius: 0">

                <div class="box-body">
                    <div class="table-responsive">
                        <table id="modelDataTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        S/N
                                    </th>
                                    <th>
                                        Author
                                    </th>
                                    <th>
                                        Topic
                                    </th>
                                    <th>
                                        Date Created
                                    </th>

                                    <th>
                                        Replies
                                    </th>
                                   
                                    <th>
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @{ int index = 0;}
                                @foreach (var item in Model.bulletinTopicLists)
                                {
                                    index += 1;
                                    <tr>
                                        <td>
                                            @index
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Author)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Topic)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DateCreated)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NumberOfResponse)
                                        </td>
                                        <td>
                                            <a asp-action="JoinBulletinBoard" asp-controller="BulletinBoard" class="btn btn-primary" asp-route-bulletinTopicId="@item.BulletinTopicId">Join</a>
                                        </td>
                                    

                                    </tr>
                                }

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>