Grant.Web/Models/ViewModels/SetupViewModel.cs
using Grant.Web.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Grant.Web.Models.ViewModels
{
    public class SetupViewModel
    {
        private DataBaseContext _context;

        public void PopulateAllDropdown(DataBaseContext context)
        {
            _context = context;
            PopulateCategoryDropDownList();
            PopulateCoAdministratorsDropDownList();


        }
        public List<Institution> Institutions { get; set; } = new List<Institution>();

        public List<Role> Roles { get; set; } = new List<Role>();

        public List<User> AdminUsers { get; set; } = new List<User>();

        public List<SelectListItem> StateSL { get; set; } = new List<SelectListItem>();

        public List<SelectListItem> RoleSL { get; set; } = new List<SelectListItem>();

        public List<SelectListItem> TitleSL { get; set; } = new List<SelectListItem>();

        public List<SelectListItem> InstitutionCategorySL { get; set; } = new List<SelectListItem>();

        [Display(Name = "Institution Name")]
        public string InstitutionName { get; set; }

        [Display(Name ="Is the Institution public?")]
        public bool IsPublic { get; set; }

        [Display(Name ="Select State")]
        public int StateId { get; set; }

        [Display(Name ="Select Institution Id")]
        public int InstitutionId { get; set; }

        [Display(Name = "Select Institution Category")]
        public int InstitutionCategoryId { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }

        [Display(Name = "Name")]
        public string FullName { get; set; }

        [Display(Name = "Select Role")]
        public int RoleId { get; set; }

        [Display(Name = "Select Title")]
        public int TitleId { get; set; }
        public CategoryAdministrator CategoryAdministrator { get; set; }
        public List<CategoryAdministrator> CategoryAdministrators { get; set; }
        public SelectList CategoryNameSL { get; set; }
        public SelectList CoAdminNameSL { get; set; }
        public int CategoryId { get; set; }
        public int CoAdminId { get; set; }
        public void PopulateCategoryDropDownList(object selectedCategory = null)
        {
            var categoryQuery = from d in _context.Category.Where(a => a.Active == true)
                                orderby d.Name // Sort by name.
                                select d;

            CategoryNameSL = new SelectList(categoryQuery.AsNoTracking(),
                        "Id", "Name", selectedCategory);
        }
        public void PopulateCoAdministratorsDropDownList(object selectedCoAdmin = null)
        {
            var coAdminQuery = from d in _context.Reviewer.Where(a => a.Active == true && a.RoleId==(int)RoleType.CoAdmin)
                                orderby d.Name // Sort by name.
                                select d;

            CoAdminNameSL = new SelectList(coAdminQuery.AsNoTracking(),
                        "Id", "Name", selectedCoAdmin);
        }
    }
}

Grant.Web/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Grant.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminHomeController : Controller
    {
        public IActionResult Index(int revid)
        {
            return View();
        }
    }
}

Grant.Web/Controllers/AdminHomeController.cs
using Grant.Web.Infrastructure;
using Grant.Web.Models;
using Grant.Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Transactions;

namespace Grant.Web.Controllers
{
    [Authorize(Policy = "MustBeAdmin")]
    public class AdminHomeController : BaseController
    {
        private readonly DataBaseContext _context;
        AdminViewModel _adminViewModel;
        Utility _utility;
        private const string Value = "Id";
        private const string Text = "Name";
        private const string Id = "Reviewer.Name";
        private const string Name = "ReviewerId";
        private const string ReviewerName = "Name";
        private const string ReviewerId = "ReviewerId";
        public const string Select = "-- Select --";
        private IHostingEnvironment _hostingEnvironment;
        public AdminHomeController(DataBaseContext context, IHostingEnvironment hostingEnvironment, Utility utility)
        {
            _context = context;
            _adminViewModel = new AdminViewModel();
            _adminViewModel.PopulateAllDropdown(_context);
            _hostingEnvironment = hostingEnvironment;
            _utility = utility;


        }
        public IActionResult Index()
        {
            if (!String.IsNullOrEmpty(ValidateUserLogin(_context)))
            {
                SetMessage(ValidateUserLogin(_context));
                return RedirectToAction("Logout", "Home");
            }

            return View();
        }

        public IActionResult ViewApplication()
        {
            try
            {
                if (!String.IsNullOrEmpty(ValidateUserLogin(_context)))
                {
                    SetMessage(ValidateUserLogin(_context));
                    return RedirectToAction("Logout", "Home");
                }
                //string adminEmail = User.FindFirstValue(ClaimTypes.Email);
                //var admin = _context.User.Where(d => d.Email == adminEmail).FirstOrDefault();
                //if (admin?.Id > 0)
                //{
                //    if (admin.Role.Name == "Admin")
                //    {
                //        _adminViewModel.PopulateReviewerExpertriateCategory(0);
                //    }
                //    else
                //    {
                //        var coAdminCategory=_context.CategoryAdministrator.Where(F => F.UserId == admin.Id && F.Active).FirstOrDefault();
                //        if (coAdminCategory?.Id > 0)
                //        {
                //            _adminViewModel.PopulateReviewerExpertriateCategory(coAdminCategory.CategoryId);
                //        }
                //    }
                //}
                SetDropdown();


            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(_adminViewModel);
        }
        [HttpPost]
        public IActionResult ViewApplication(int CategoryId, int ThemeId, int SessionId)
        {
            try
            {
                if (SessionId <= 0)
                {
                    SetMessage("Please you must select atleast research cycle.");
                    return View(_adminViewModel);
                }
                string adminEmail = User.FindFirstValue(ClaimTypes.Email);
                var admin = _context.User.Where(d => d.Email == adminEmail).FirstOrDefault();
                List<ApplicationList> list = new List<ApplicationList>();
                var applications = new List<ApplicantThematic>();
                if (SessionId > 0 && CategoryId == 0 && ThemeId == 0)
                {


                    if (admin.RoleId != (int)RoleType.Admin && admin.RoleId != (int)RoleType.SuperAdmin)
                    {
                        var categoryAdmin = _context.CategoryAdministrator.Where(f => f.User.Id == admin.Id && f.Active).FirstOrDefault();
                        if (categoryAdmin == null)
                        {
                            SetMessage("Category has not been assigned to you");
                            return RedirectToAction("ViewApplication");
                        }
                        applications = _context.ApplicantThematic.Where(f => f.SessionId == SessionId && f.Theme.CategoryId == categoryAdmin.CategoryId).ToList();
                    }
                    else
                    {
                        applications = _context.ApplicantThematic.Where(f => f.SessionId == SessionId).ToList();
                    }

                }
                else if (SessionId > 0 && CategoryId > 0 && ThemeId == 0)
                {
                    applications = _context.ApplicantThematic.Where(f => f.Theme.CategoryId == CategoryId && f.SessionId == SessionId).ToList();
                }
                else if (SessionId > 0 && CategoryId > 0 && ThemeId > 0)
                {
                    applications = _context.ApplicantThematic.Where(f => f.ThemeId == ThemeId && f.SessionId == SessionId).ToList();
                }

                //_adminViewModel.PopulateReviewerExpertriateCategory(CategoryId);
                SetDropdown();

                _adminViewModel.ThemeId = ThemeId;
                _adminViewModel.Theme = _context.Theme.Where(f => f.Id == ThemeId).FirstOrDefault();
                if (applications.Count > 0)
                {

                    for (int i = 0; i < applications.Count; i++)
                    {
                        List<int> reviewerIdList = new List<int>();
                        var thematicapplicant = applications[i];
                        var conceptNote = _context.ConceptNote.Where(g => g.ApplicantThemeId == thematicapplicant.Id).FirstOrDefault();
                        if (conceptNote != null && conceptNote.Submitted)
                        {
                            ApplicationList applicationList = new ApplicationList();
                            var applicantId = applications[i].ApplicantId;

                            var applicant = _context.Applicant.Where(f => f.Id == applicantId).FirstOrDefault();
                            var Person = _context.Person.Where(j => j.Id == applicant.PersonId).FirstOrDefault();
                            applicationList.ApplicantThematic = applications[i];
                            applicationList.Person = Person;
                            var applicantReviewerList = _context.ApplicantReviewer.Where(f => f.ApplicantThematicId == thematicapplicant.Id && f.TypeId == (int)Types.ConceptNote).ToList();
                            if (applicantReviewerList.Count > 0)
                            {
                                List<Reviewer> reviewerList = new List<Reviewer>();
                                for (int j = 0; j < applicantReviewerList.Count; j++)
                                {
                                    var reviewerId = applicantReviewerList[j].ReviewerId;
                                    var reviewer = _context.Reviewer.Where(f => f.Id == reviewerId).FirstOrDefault();
                                    reviewerList.Add(reviewer);
                                }
                                applicationList.Reviewers = reviewerList;
                            }
                            else
                            {
                                List<Reviewer> reviewerList = new List<Reviewer>();
                                applicationList.Reviewers = reviewerList;
                            }
                            applicationList.Category = applications[i].Theme.Category;
                            applicationList.Theme = applications[i].Theme;
                            //applicationList.Category = _context.Category.Where(f => f.Id == CategoryId).FirstOrDefault();
                            //applicationList.Theme = _context.Theme.Where(f => f.Id == ThemeId).FirstOrDefault();
                            //For conceptNote accessors ar selected by category and not be thematicArea
                            var reviewerStrengthList = _context.ReviewerThematicStrenght.Where(d => d.Theme.CategoryId == applicationList.Category.Id
                            && d.Reviewer.InstitutionId != thematicapplicant.Applicant.Person.InstitutionId).ToList();

                            if (reviewerStrengthList?.Count > 0)
                            {
                                List<AssessorDropdown> assessorDropdownList = new List<AssessorDropdown>();
                                foreach (var item in reviewerStrengthList)
                                {
                                    //ensure a reviewer is added to dropdown list once irrespective his numerous strenght in many thematic area of thesame category
                                    if (!reviewerIdList.Contains(item.ReviewerId))
                                    {
                                        reviewerIdList.Add(item.ReviewerId);
                                        var name = "";
                                        var perAssessor = _context.ApplicantReviewer.Where(f => f.ApplicantThematic.Theme.CategoryId == applicationList.Category.Id
                                        && f.TypeId == (int)Types.ConceptNote && f.ReviewerId == item.ReviewerId && f.ApplicantThematic.SessionId == SessionId).ToList();
                                        name = item.Reviewer.Name + "-" + "(" + perAssessor.Count + ")";
                                        AssessorDropdown assessorDropdown = new AssessorDropdown();
                                        assessorDropdown.ReviewerId = item.ReviewerId;

Grant.Web/Views/AdminHome/AddReviewer.cshtml
@model Grant.Web.Models.ViewModels.AdminViewModel
@{
    ViewData["Title"] = "Add Assessor";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    @if (@TempData["Message"] != null)
            {
        <div class="callout " style="color: white">

            @Html.Partial("_Message", TempData["Message"])

        </div>
    }
</section>

<section class="content">

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Assessors  <span class="text-muted text-sm">/ Add Assessor </span></h1>
        <hr class="mt-0 mb-2" />
    </div>

    <div class="row justify-content-center" style="margin-bottom: 30px">
            
            <div class="col-md-8">
                <!-- Horizontal Form -->
                <div class="card animated fadeInUp delay-1s" style="">
                    
                    <div class="card-body">

                    <!-- form start -->
                        <form asp-action="AddReviewer" asp-antiforgery="true" enctype="multipart/form-data" class="form-horizontal">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="box-body">

                            <div class="box-body">
                                <div class="form-group">


                                    <label asp-for="Reviewer.TitleId" class="col-sm-12">Title</label>
                                    <div class="col-sm-12">
                                        <select asp-for=Reviewer.TitleId class="form-control"
                                                asp-items=Model.TitleNameSL required>
                                            <option value="">-- Select Title --</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">


                                    <label asp-for="Reviewer.Name" class="col-sm-12">Name</label>
                                    <div class="col-sm-12">
                                        <input asp-for="Reviewer.Name" class="form-control" />
                                        <span asp-validation-for="Reviewer.Name" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Reviewer.Email" class="col-sm-12">Email</label>
                                    <div class="col-sm-12">
                                        <input type="email" asp-for="Reviewer.Email" class="form-control" id="email" />
                                        <span asp-validation-for="Reviewer.Email" class="text-danger"></span>
                                        <label style="color:red" id="errorEmail"></label>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label asp-for="Reviewer.PhoneNo" class="col-sm-12">Phone No.</label>
                                    <div class="col-sm-12">
                                        <input asp-for="Reviewer.PhoneNo" class="form-control" pattern="^0\d{10}" />
                                        <span asp-validation-for="Reviewer.PhoneNo" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-12">Higher Education Sector</label>
                                    <div class="col-sm-12">
                                        <select id="InstitutionCategoryId" asp-for=InstitutionCategoryId class="form-control"
                                                asp-items=Model.InstitutionCategoryNameSL required>
                                            <option value="">-- Select Higher Education Sector --</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group" style="display:none" id="institutionDiv">
                                    <label class="col-sm-12"> Institution</label>
                                    <div class="col-sm-12">
                                        <select asp-for="Reviewer.InstitutionId" class="form-control" id="InstitutionId"
                                                name="Reviewer.InstitutionId" data-url="@Url.Action("GetInstitution")"></select>
                                        <span asp-validation-for="Reviewer.InstitutionId" class="text-danger"></span>
                                    </div>
                                </div>
                                <br />
                                @*<div class="form-group">
            <label asp-for="User.UserName" class="col-sm-12">Username</label>
            <div class="col-sm-12">
                <input asp-for="User.UserName" class="form-control" placeholder="surname/firstname" />
                <span asp-validation-for="User.UserName" class="text-danger"></span>
            </div>
        </div>*@



                            </div>



                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer text-center">

                            <button type="submit" class="btn btn-success pull-right" id="saveBtn">Save</button>
                        </div>
                        <!-- /.box-footer -->
                    </form>
                    </div>

                </div>
                <!-- /.box -->

            </div>

     </div>
</section>
<script src="~/theme/bower_components/jquery/dist/jquery.js"></script>
<script>
    $(document).ready(function () {
                    //check for existing email
                            $('#email').on('blur', function () {
                    var email = $('#email').val();
                    if (email != null || email != '' || email != undefined) {
                        $.ajax({
                            type: 'POST',
                            url: '@Url.Action("ExistingEmail", "AdminHome")',// we are calling json method
                            dataType: 'json',
                            //contentType:"application/json",
                            data: { email: email },
                            success: function (result) {
                                if (!result.isError && result.message != null) {
                                    $('#saveBtn').prop('disabled', true);
                                    $('#errorEmail').text(result.message);
                                }
                                else {
                                    $('#saveBtn').prop('disabled', false);
                                    $('#errorEmail').text("");
                                }


                            },
                            error: function (ex) {
                                alert('Failed to Checkout.' + result.message);

                            }
                        });
                    }
                })
    })
                $(function () {
            $("#InstitutionCategoryId").change(function () {
                var v = $(this).val();
                var url = $("#InstitutionId").data("url") + '?value=' + v;
                $("#institutionDiv").hide();
                $.getJSON(url, function (institutionList) {
                    if (institutionList != null) {
                        $("#institutionDiv").show();
                        $("#InstitutionId").empty();

                        $("#InstitutionId").append('<option value="' + 0 + '">' +
                            '-- Select Institution --' + '</option>');
                        $.each(institutionList, function (i, inst) {
                            $("#InstitutionId").append('<option value="' + inst.value + '">' +
                                inst.text + '</option>');
                        });
                    }



                });

            })

        })
</script>

Grant.Web/Views/AdminHome/ConceptNoteAccessorDistribution.cshtml
@model Grant.Web.Models.ViewModels.AdminViewModel
@using Grant.Web.Infrastructure
@{
    ViewData["Title"] = "Accessor Distribution";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: red">

            @Html.Partial("_Message", TempData["Message"])

        </div>
    }

</section>

<section class="content">

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Concept Notes <span class="text-muted text-sm">/ Auto Distribution </span></h1>
        <hr class="mt-0 mb-2" />
    </div>

    <div class="row justify-content-center" style="margin-bottom: 30px">

        <div class="col-md-12">

            <div class="card animated fadeInUp delay-1s" style="">

                <div class="card-body">
                    <div class="" style="margin-left: 3px !important; margin-bottom: 20px">


                        <!-- Horizontal Form -->
                        <div class="box box-danger" style="border-top-color: #fff; border-radius: 0px">

                            <div class="box-body">
                                <div class="table-responsive">
                                    <table id="modelDataTable" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>S/N</th>
                                                <th>
                                                    Category
                                                </th>

                                                <th>
                                                    Total Submission
                                                </th>
                                                <th>
                                                    Assigned
                                                </th>
                                                <th>
                                                    Unassigned
                                                </th>




                                            </tr>
                                        </thead>
                                        <tbody>
                                            @for (int i = 0; i < Model.AccessorDistributionCount.Count; i++)
                                            {
                                                var index = i + 1;
                                                var cId = Utility.Encrypt(Model.AccessorDistributionCount[i].Category.Id.ToString());
                                                <tr>
                                                    <td>@index</td>
                                                    <td>
                                                        <a asp-action="ActivatAccessor" asp-controller="AdminHome"  asp-route-cId=@cId>@Html.DisplayFor(modelItem => Model.AccessorDistributionCount[i].Category.Name)</a>

                                                    </td>

                                                    <td>
                                                        
                                                        <a asp-action="SubmittedConceptNoteByCategory" asp-controller="AdminHome" asp-route-cId=@cId>@Html.DisplayFor(modelItem => Model.AccessorDistributionCount[i].TotalSubmission)</a>
                                                    </td>
                                                    <td>
                                                        <a asp-action="AssignedConceptNoteByCategory" asp-controller="AdminHome" asp-route-cId=@cId>@Html.DisplayFor(modelItem => Model.AccessorDistributionCount[i].TotalAssigned)</a>
                                                        
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => Model.AccessorDistributionCount[i].TotalUnassigned)
                                                    </td>


                                                </tr>
                                            }

                                    </table>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="box-footer mt-3 text-center">
                        <button class="btn btn-success pull-right" id="distribute">Distribute</button>
                    </div>



                </div>

            </div>

        </div>

    </div>


</section>
<script src="~/theme/bower_components/jquery/dist/jquery.js"></script>
@section Scripts{
    <script>

    $(document).ready(function () {
        $('#distribute').on('click', function () {

                $('#distribute').attr('disabled', true);
                $('#distribute').text("Distributing...");
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("AutoDustribution", "AdminHome")', // we are calling json method
                    dataType: 'json',
                    data: { },
                    success: function (result) {
                        if (!result.isError && result.message != null) {
                            alert(result.message);
                            window.location.reload(true);
                        }

                    },
                    error: function (ex) {
                        $('#distribute').attr('disabled', false);
                        $('#distribute').text("Distribute");
                        alert('Failed to Open Theme.' + ex);
                    }
                });
        })
    })

    </script>
}

Grant.Web/Views/AdminHome/EditReviewer.cshtml
@model Grant.Web.Models.ViewModels.AdminViewModel
@{
    ViewData["Title"] = "Edit Assessor";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<section class="content-header">
    @if (@TempData["Message"] != null)
            {
        <div class="callout " style="color: white">

            @Html.Partial("_Message", TempData["Message"])

        </div>
    }
</section>
<section class="content">
    <div class="container">
        <div class="col-md-12">
            <!-- Horizontal Form -->
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">Add Assessor </h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form asp-action="UpdateReviewer" asp-antiforgery="true" enctype="multipart/form-data" class="form-horizontal">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Reviewer.Id" />
                    <div class="box-body">

                        <div class="box-body">
                            <div class="form-group">
                                <label asp-for="Reviewer.Name" class="col-sm-4 control-label">Name</label>
                                <div class="col-sm-8">
                                    <input asp-for="Reviewer.Name" class="form-control" />
                                    <span asp-validation-for="Reviewer.Name" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Reviewer.Email" class="col-sm-4 control-label">Email</label>
                                <div class="col-sm-8">
                                    <input type="email" asp-for="Reviewer.Email" class="form-control" />
                                    <span asp-validation-for="Reviewer.Email" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label asp-for="Reviewer.PhoneNo" class="col-sm-4 control-label">Phone No.</label>
                                <div class="col-sm-8">
                                    <input asp-for="Reviewer.PhoneNo" class="form-control" />
                                    <span asp-validation-for="Reviewer.PhoneNo" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label asp-for="Reviewer.Active" class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="Reviewer.Active" />
                                </div>
                            </div>



                        </div>



                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">

                        <button type="submit" class="btn btn-danger pull-right">Save</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
            <!-- /.box -->

        </div>
    </div>
</section>