Grant.Web/Models/ProposalAssessment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Grant.Web.Models
{
    public class ProposalAssessment
    {
        public int Id { get; set; }
        public int ApplicantThematicId { get; set; }
        public int ReviewerId { get; set; }
        //public int AssessmentGuideId { get; set; }
        public decimal? ApprovedBudget { get; set; }
        public bool Approved { get; set; }
        public decimal Score { get; set; }
        public int ProposalId { get; set; }
        public string ReasonForDissapproval { get; set; }
        public string Remark { get; set; }
        public int ProposalScoringId { get; set; }
        public virtual ProposalScoring ProposalScoring { get; set; }
        public virtual ApplicantThematic ApplicantThematic { get; set; }
        public virtual Reviewer Reviewer { get; set; }
        public virtual ICollection<AssessmentGuide> AssessmentGuide { get; set; }
        public virtual Proposal Proposal { get; set; }
        public bool IsReconcilled { get; set; }

    }
}

Grant.Web/Controllers/ReviewerHomeController.cs
using Grant.Web.Infrastructure;
using Grant.Web.Models;
using Grant.Web.Models.ViewModels;
using ICSharpCode.SharpZipLib.Zip;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;

namespace Grant.Web.Controllers
{
    [Authorize(Policy = "MustBeReviewer")]
    public class ReviewerHomeController : BaseController
    {
        private readonly DataBaseContext _context;
        AdminViewModel _adminViewModel;
        Utility _utility;
        private const string Value = "Id";
        private const string Text = "Name";
        private IHostingEnvironment _hostingEnvironment;
        private IConfiguration _configuration;
        private string baseUrl;
        public ReviewerHomeController(DataBaseContext context, IHostingEnvironment hostingEnvironment, Utility utility, IConfiguration configuration)
        {
            _context = context;
            _adminViewModel = new AdminViewModel();
            _adminViewModel.PopulateAllDropdown(_context);
            _hostingEnvironment = hostingEnvironment;
            _utility = utility;
            _configuration = configuration;
            baseUrl = _configuration.GetValue<string>("Url:onlineVerificationRoot");


        }
        public IActionResult Index()
        {
            try
            {
                List<ProposalAssessment> proposalAssessment = new List<ProposalAssessment>();
                List<ApplicantReviewer> applicantReviewerList = new List<ApplicantReviewer>();
                string reviewerEmail = User.FindFirstValue(ClaimTypes.Email);
                var reviewer = _context.Reviewer.Where(d => d.Email == reviewerEmail).FirstOrDefault();
                var reviewerProposalAssessment = _context.ProposalAssessment.Where(f => f.ReviewerId == reviewer.Id && f.ApplicantThematic.Session.ActiveForApplication && !f.IsReconcilled).ToList();
                if (reviewerProposalAssessment.Count > 0)
                {
                    for (int i = 0; i < reviewerProposalAssessment.Count; i++)
                    {
                        var isSubmitted = AssessmentIsSubmitted(reviewerProposalAssessment[i].ApplicantThematicId, reviewer.Id, (int)Types.Proposal);
                        //only submitted assessments are considered
                        if (isSubmitted)
                        {
                            int Id = reviewerProposalAssessment[i].ApplicantThematicId;
                            var myProposalAssessment = reviewerProposalAssessment[i];
                            var allMyProposalAssessment = _context.ProposalAssessment.Where(h => h.ApplicantThematicId == Id).ToList();
                            var orderedScore = allMyProposalAssessment.OrderBy(O => O.Score).Select(o => o.Score).ToList();
                            var orderedMax = orderedScore.LastOrDefault();
                            var orderedMin = orderedScore.FirstOrDefault();
                            var scoreDifference = orderedMax - orderedMin;
                            //filter the proposals that require reconcillation
                            if (scoreDifference > 10)
                            {
                                proposalAssessment.Add(myProposalAssessment);
                            }
                        }
                      
                    }
                }
                var applicantReviewer = _context.ApplicantReviewer.Where(d => d.ReviewerId == reviewer.Id && d.TypeId == (int)Types.ConceptNote && d.ApplicantThematic.Session.ActiveForApplication && !d.IsReconciled && d.ConceptNoteMark!=null).ToList();
                if (applicantReviewer?.Count > 0)
                {
                    foreach (var item in applicantReviewer)
                    {

                        var isSubmitted=AssessmentIsSubmitted(item.ApplicantThematicId, reviewer.Id, (int)Types.ConceptNote);
                        //only submitted assessments are considered
                        if (isSubmitted)
                        {
                            var allApplicantThematicRecore = _context.ApplicantReviewer.Where(f => f.ApplicantThematicId == item.ApplicantThematicId && f.TypeId == (int)Types.ConceptNote).ToList();
                            var orderedScore = allApplicantThematicRecore.Where(f => f.ConceptNoteMark != null).OrderBy(f => f.ConceptNoteMark).Select(f => f.ConceptNoteMark).ToList();
                            var orderedMax = orderedScore.LastOrDefault();
                            var orderedMin = orderedScore.FirstOrDefault();
                            var scoreDifference = orderedMax - orderedMin;
                            //filter the Concept Notes that require reconcillation
                            if (scoreDifference > 10)
                            {
                                applicantReviewerList.Add(item);
                            }
                        }
                       
                    }
                }
                _adminViewModel.ProposalAssessments = proposalAssessment;
                _adminViewModel.ApplicantReviewers = applicantReviewerList;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(_adminViewModel);
        }
        public IActionResult ViewCoReviewer(string id)
        {
            try
            {
                string reviewerEmail = User.FindFirstValue(ClaimTypes.Email);
                int applicantthematicId = Convert.ToInt32(Utility.Decrypt(id));
                var reviewer = _context.Reviewer.Where(d => d.Email == reviewerEmail).FirstOrDefault();
                _adminViewModel.ProposalAssessments = _context.ProposalAssessment.Where(t => t.ApplicantThematicId == applicantthematicId && t.ReviewerId != reviewer.Id).ToList();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(_adminViewModel);
        }
        public IActionResult ViewCoReviewerConceptNote(string id)
        {
            List<ReviewerScore> reviewerScoreList = new List<ReviewerScore>();
            try
            {
                string reviewerEmail = User.FindFirstValue(ClaimTypes.Email);
                var reviewer = _context.Reviewer.Where(d => d.Email == reviewerEmail).FirstOrDefault();
                int applicantthematicId = Convert.ToInt32(Utility.Decrypt(id));
                _adminViewModel.ApplicantReviewers = _context.ApplicantReviewer.Where(t => t.ApplicantThematicId == applicantthematicId && t.ReviewerId != reviewer.Id && t.TypeId==(int)Types.ConceptNote).ToList();
                if (_adminViewModel.ApplicantReviewers?.Count > 0)
                {
                    for(int i=0;i< _adminViewModel.ApplicantReviewers.Count; i++)
                    {
                        ReviewerScore reviewerScore = new ReviewerScore();

                        var reviewerId = _adminViewModel.ApplicantReviewers[i].ReviewerId;

                        reviewerScore.Reviewer= _context.Reviewer.Where(f => f.Id == reviewerId).FirstOrDefault();
                        reviewerScore.Score = Convert.ToString(_adminViewModel.ApplicantReviewers[i].ConceptNoteMark);
                        reviewerScore.ApplicantThematic = _adminViewModel.ApplicantReviewers[i].ApplicantThematic;
                        reviewerScore.Comment=_context.ProposalScoring.Where(d => d.ApplicantThematicId == applicantthematicId && d.ReviewerId == reviewerId && d.TypeId == (int)Types.ConceptNote).Select(d=>d.Remark).FirstOrDefault();
                        reviewerScoreList.Add(reviewerScore);
                    }
                }
                _adminViewModel.ReviewerScores = reviewerScoreList;

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(_adminViewModel);
        }
        public IActionResult ViewMyApplicantConceptNote()
        {
            try
            {
                List<ApplicationList> list = new List<ApplicationList>();
                
                string reviewerEmail = User.FindFirstValue(ClaimTypes.Email);
                var reviewer = _context.Reviewer.Where(d => d.Email == reviewerEmail).FirstOrDefault();
                if (reviewer != null)
                {
                    var activeSessionForApplication = _context.Session.Where(f => f.ActiveForApplication).LastOrDefault();
                    if (activeSessionForApplication == null)
                    {
                        SetMessage("No Active Research Cycle at the Moment.");
                        return RedirectToAction("Index");
                    }
                    var listOfApplicant = _context.ApplicantReviewer.Where(d => d.ReviewerId == reviewer.Id && d.TypeId == (int)Types.ConceptNote && d.ApplicantThematic.SessionId== activeSessionForApplication.Id).ToList();
                    if (listOfApplicant.Count > 0)
                    {
                        for (int i = 0; i < listOfApplicant.Count; i++)
                        {
                            ApplicationList applicationList = new ApplicationList();
                            Category category = new Category();
                            var applicantthematicId = listOfApplicant[i].ApplicantThematicId;
                            var applicantThematic = _context.ApplicantThematic.Where(g => g.Id == applicantthematicId).FirstOrDefault();
                            var applicant = _context.Applicant.Where(f => f.Id == applicantThematic.ApplicantId).FirstOrDefault();

Grant.Web/Views/ReviewerHome/GroupedConceptNoteSubmission.cshtml
@model Grant.Web.Models.ViewModels.AdminViewModel
@using Grant.Web.Infrastructure
@{
    ViewData["Title"] = "ViewMyApplicantConceptNote";
    //Layout = "~/Views/Shared/_ReviewerLayout.cshtml";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<section class="content-header bd-top" style="padding-top: 0; background-color: #fff">

    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">

            @Html.Partial("_Message", TempData["Message"])

        </div>
    }
</section>

<section class="content">

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Concept Note Submissions By Thematic Area</h1>
        <div class="avatar-group mt-3">
        </div>
    </div>

    <div class="row justify-content-center" style="margin-bottom: 30px">
        <div class="col-md-10">
            <!-- Horizontal Form -->
            <div class="card animated fadeInUp delay-1s " style="">

                <div class="card-body">
                    <div class="table-responsive">
                        <table id="modelDataTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>S/N</th>
                             
                                    <th>
                                        Thematic Area
                                    </th>
                                    <th>
                                        Count
                                    </th>
                                   


                                    <th>
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @{ int index = 0;}
                                @foreach (var item in Model.GroupSubmissionByTHematicAreas)
                                {
                                    var id = Utility.Encrypt(item.ThemeId.ToString());
                                    var rId = Utility.Encrypt(item.ReviewerId.ToString());
                                    index += 1;
                                    <tr>
                                        <td>@index</td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ThematicName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Count)
                                        </td>

                                        <td>
                                            <a asp-action="DownloadGroupConceptNote" asp-controller="ReviewerHome" class="btn btn-success" asp-route-id=@id asp-route-rId=@rId>Download</a>
                                        </td>


                                    </tr>
                                }

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Grant.Web/Views/ReviewerHome/ProposalAssessment.cshtml
@model Grant.Web.Models.ViewModels.AdminViewModel
@{
    ViewData["Title"] = "Full Proposal Assessment";
    //Layout = "~/Views/Shared/_ReviewerLayout.cshtml";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content-header">
    @if (@TempData["Message"] != null)
            {
        <div class="callout " style="color: white">

            @Html.Partial("_Message", TempData["Message"])

        </div>
    }
</section>
<section class="content">

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Full Proposal Assessment</h1>
        <div class="avatar-group mt-3">
        </div>
    </div>

    <div class="row justify-content-center">

            <div class="col-md-10">
                <!-- Horizontal Form -->
                <div class="card animated fadeInUp delay-1s">

                    <div class="card-body">
                        <br />
                        <input type="hidden" asp-for="Person.Id" />
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="Person.Name" class="col-sm-4 control-label"></label>
                                        <div class="col-sm-8">
                                            <input asp-for="Person.Name" class="form-control" disabled />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="Person.PhoneNo" class="col-sm-4 control-label"></label>
                                        <div class="col-sm-8">
                                            <input asp-for="Person.PhoneNo" class="form-control" disabled />
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="Person.Email" class="col-sm-4 control-label"></label>
                                        <div class="col-sm-8">
                                            <input asp-for="Person.Email" class="form-control" disabled />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="Proposal.SubmittedBudget" class="col-sm-4 control-label"> Amount</label>
                                        <div class="col-sm-8">
                                            <input asp-for="Proposal.SubmittedBudget" class="form-control" disabled />
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>

                    </div>




                </div>

            </div>
            <div class="col-md-12">
                <!-- Horizontal Form -->
                <div class="box box-danger">
                    <div class="box-header with-border">
                        <h3 class="box-title">Full Proposal Assessment</h3>
                    </div>
                    <div class="box-body">
                        <br />
                        <br />
                        <input type="hidden" asp-for="Proposal.ProposalUrl" id="proposalUrl" />
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-lg-4">
                                    <button id="prebtn" class="btn btn-danger pull-left"> Previous</button>
                                </div>
                                <div class="col-lg-4 text-center">
                                    <span class="page-info white-text text-center">
                                        Page <span id="page-num"> </span> of <span id="page-count"></span>
                                    </span>

                                </div>
                                <div class="col-lg-4">
                                    <button id="nxtbtn" class="btn btn-danger pull-right"> Next</button>
                                </div>
                            </div>

                        </div>
                        <div class="col-md-12 text-center" style="height:700px">
                            <canvas id="pdfrender" style="height:100%; width:100%"></canvas>
                        </div>

                    </div>




                </div>

            </div>
        <form asp-action="ProposalAssessment" asp-controller="ReviewerHome" method="POST" role="form" class="form-horizontal">
            <div class="col-md-12">
                <!-- Horizontal Form -->
                <div class="box box-danger">
                    <div class="box-body">
                        <table id="modelDataTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Parameter
                                    </th>
                                    <th>
                                        Max Score
                                    </th>
                                    <th>
                                        Actual Score
                                    </th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.ScoreAssessments)
                                {
                                    <tr>
                                        @Html.HiddenFor(modelItem => item.AssessmentGuide.Id)
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AssessmentGuide.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.AssessmentGuide.MaxScore)
                                        </td>
                                        <td>
                                            @Html.EditorFor(modelItem => item.Score)
                                        </td>

                                    </tr>
                                }

                        </table>
                    </div>

                </div>
            </div>
            <div class="col-md-12">
                <!-- Horizontal Form -->
                <div class="box box-danger">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="ProposalAssessment.ApprovedBudget" class="col-sm-4 control-label"> Approved Budget</label>
                                    <div class="col-sm-8">
                                        <input asp-for="ProposalAssessment.ApprovedBudget" class="form-control" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="ProposalAssessment.Approved" class="col-sm-4 control-label"> Approved</label>
                                    <div class="col-sm-8">
                                        <input type="checkbox" asp-for="ProposalAssessment.Approved" />
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
            <div class="card-footer">

                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </form>

    </div>
</section>
<script src="~/theme/bower_components/jquery/dist/jquery.js"></script>
<script src="~/PdfReader/pdf.js"></script>
<script>
    let pdfDoc = null,
        pageNum = 1,
        pageIsRendering = false,
        pageNumIsPending = null;

    const scale = 1,
        canvas = document.querySelector("#pdfrender"),
        ctx = canvas.getContext("2d");

    const url = $('#proposalUrl').val();

    //var ctx = canvas[0].getContext("2d");

    pdfjsLib.getDocument(url)
        .promise
        .then((pdfDoc_) => {
            pdfDoc = pdfDoc_;
            //set the total number of pages in a span
            $("#page-count").text(pdfDoc.numPages);

            renderPage(pageNum);//init at one
        })
        .catch((err) => console.error(err));

    const renderPage = (num) => {
        pageIsRendering = true;//tell the app that a page is rendering
        //get the page
        pdfDoc.getPage(num)
            .then((page) => {
                //set the scale of the pdf
                const viewport = page.getViewport(scale);
                canvas.height = viewport.height;
                canvas.width = viewport.width;

                const renderCtx = {
                    canvasContext: ctx,
                    viewport
                };

                page.render(renderCtx)
                    .promise
                    .then(() => {
                        pageIsRendering = false;

                        if (pageNumIsPending !== null) {
                            renderPage(pageNumIsPending);
                            pageNumIsPending = null;
                        }
                    })
                    .catch((err) => console.error(err));

                //output the current page
                $("#page-num").text(num);
            })
            .catch((err) => console.error(err));
    };


    function queueRenderPage (num) {
        if (pageIsRendering)
            pageNumIsPending = null;
        else renderPage(num);
    };


    $("#nxtbtn").on('click', function () {
        if (pageNum >= pdfDoc.numPages) {
            return;

        }
        pageNum++;
        queueRenderPage(pageNum);

    });


    $("#prebtn").on('click', function () {
        if (pageNum <= 1) {
            return;

        }
        pageNum--;
        queueRenderPage(pageNum);

    });
</script>

Grant.Web/Views/ReviewerHome/ViewCoReviewer.cshtml
@model Grant.Web.Models.ViewModels.AdminViewModel
@using Grant.Web.Infrastructure
@{
    ViewData["Title"] = "Index";
    //Layout = "~/Views/Shared/_ReviewerLayout.cshtml";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<section class="content-header">
    @if (@TempData["Message"] != null)
    {
        <div class="callout " style="color: white">

            @Html.Partial("_Message", TempData["Message"])

        </div>
    }
</section>

<section class="content">

    <div class="ct-page-title">
        <h1 class="ct-title" id="content">Review Co-Assessor(s) Scoresheet</h1>
        <div class="avatar-group mt-3">
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-10">
            <!-- Horizontal Form -->
            <div class="card">

                <div class="card-body">
                    <table id="modelDataTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>

                                <th>
                                    Name
                                </th>
                                <th>
                                    Phone
                                </th>
                                <th>
                                    E-mail
                                </th>

                                <th>
                                    Proposal Score
                                </th>
                                <th>
                                    Approved Budget
                                </th>
                                <th>
                                    Comment
                                </th>
                                <th>
                                    View
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ProposalAssessments)
                            {
                                var id = Utility.Encrypt(item.ApplicantThematic.Id.ToString());
                                var reviewer = Utility.Encrypt(item.Reviewer.Id.ToString());
                                <div class="modal fade" id="commentnmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Comment Box</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="form-group">
                                                    <textarea class="col-md-12" readonly>@item.Remark</textarea>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>


                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <tr>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.Reviewer.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Reviewer.PhoneNo)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.Reviewer.Email)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Score)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ApprovedBudget)
                                    </td>





                                    @if (item.Remark != null)
                                    {
                                        <td><button class="btn btn-primary" data-toggle="modal" data-target="#commentnmodal" id="showEditSession">Comment</button></td>
                                    }
                                    else
                                    {
                                        <td>
                                            No Comment
                                        </td>
                                    }
                                    <td>
                                        <a asp-action="CoReviewerAssessment" asp-controller="ReviewerHome" class="btn btn-success" asp-route-applicantthematicIdString=@id asp-route-reviewerIdString=@reviewer>Review</a>
                                    </td>


                                </tr>
                            }

                    </table>
                </div>
            </div>
        </div>
    </div>

</section>